### ISSUE TITLE
Headers to dict?

### ISSUE THREAD

**Issue by CMethoddata** [gridsmartercities/aws-lambda-decorators#128]
Hi,

Love the work you guys have done, this is awesome. I am trying to extract my "Authorization" from my headers (I see you currently do not support Bearer).

I am trying the following:
```python
@extract_from_event(parameters=[

    Parameter(
        path="/headers[json]/Authorization", validators=[Mandatory], var_name="auth")
])
```
and receiving the following error:

```json
{"message": "Error extracting parameters"}
```

any ideas?

**Comment by eulogio-gutierrez** [comment]
Hi Connor,

Thanks for your comment! it is really appreciated. Apologies for the late reply, it has been a bit hectic lately.

I would say you dont need to add the [json] decoder to the headers path, as "headers" is a dictionary and not a string that contains JSON.

You can see an example of extracting the Authorization header from the lambda event here (remove the sub part if you want the full token, and the [jwt] decoder if you have a bearer token as we cannot do those yet):
https://github.com/gridsmartercities/aws-lambda-decorators/blob/073797e35c4babaac3ec0b0ed6e75f9ab6088f6d/examples/examples.py#L68

And in case you ever need it, you can see an example of using the [json] decoder here: https://github.com/gridsmartercities/aws-lambda-decorators/blob/073797e35c4babaac3ec0b0ed6e75f9ab6088f6d/examples/test_examples.py#L102
 
Regards,
Eulogio

**Comment by CMethoddata** [comment]
No worries! Thanks for the reply Eulogio! I will give this a try.

Thanks,
Connor
